// 30 Predetermined Rounds - Each round contains exactly 30 players in fixed positions
// Players appear 12-18 times across all rounds for balanced gameplay
// Round 1: positions 0-29, Round 2: positions 0-29, etc.
// Each player maintains their exact position when a round is reloaded

const PREDETERMINED_ROUNDS = {
    1: [
        { id: 1, name: "Lionel Messi", position: 0 },
        { id: 2, name: "Cristiano Ronaldo", position: 1 },
        { id: 3, name: "Kylian Mbappé", position: 2 },
        { id: 4, name: "Erling Haaland", position: 3 },
        { id: 5, name: "Neymar", position: 4 },
        { id: 6, name: "Mohamed Salah", position: 5 },
        { id: 7, name: "Vinícius Júnior", position: 6 },
        { id: 8, name: "Harry Kane", position: 7 },
        { id: 9, name: "Sadio Mané", position: 8 },
        { id: 10, name: "Son Heung-min", position: 9 },
        { id: 21, name: "Kevin De Bruyne", position: 10 },
        { id: 22, name: "Jude Bellingham", position: 11 },
        { id: 23, name: "Pedri", position: 12 },
        { id: 24, name: "Rodri", position: 13 },
        { id: 25, name: "Phil Foden", position: 14 },
        { id: 41, name: "Virgil van Dijk", position: 15 },
        { id: 42, name: "Sergio Ramos", position: 16 },
        { id: 43, name: "Antonio Rüdiger", position: 17 },
        { id: 44, name: "Rúben Dias", position: 18 },
        { id: 45, name: "Marquinhos", position: 19 },
        { id: 11, name: "Robert Lewandowski", position: 20 },
        { id: 12, name: "Victor Osimhen", position: 21 },
        { id: 26, name: "Bernardo Silva", position: 22 },
        { id: 27, name: "Luka Modrić", position: 23 },
        { id: 46, name: "João Cancelo", position: 24 },
        { id: 47, name: "Trent Alexander-Arnold", position: 25 },
        { id: 13, name: "Antoine Griezmann", position: 26 },
        { id: 28, name: "Toni Kroos", position: 27 },
        { id: 48, name: "Achraf Hakimi", position: 28 },
        { id: 14, name: "Lautaro Martínez", position: 29 }
    ],
    2: [
        { id: 15, name: "Julián Álvarez", position: 0 },
        { id: 16, name: "Viktor Gyökeres", position: 1 },
        { id: 17, name: "Bukayo Saka", position: 2 },
        { id: 18, name: "Khvicha Kvaratskhelia", position: 3 },
        { id: 19, name: "Marcus Rashford", position: 4 },
        { id: 20, name: "Rafael Leão", position: 5 },
        { id: 29, name: "Joshua Kimmich", position: 6 },
        { id: 30, name: "Declan Rice", position: 7 },
        { id: 31, name: "Martin Ødegaard", position: 8 },
        { id: 32, name: "Bruno Fernandes", position: 9 },
        { id: 49, name: "Theo Hernández", position: 10 },
        { id: 50, name: "Jules Koundé", position: 11 },
        { id: 51, name: "William Saliba", position: 12 },
        { id: 52, name: "Gabriel Magalhães", position: 13 },
        { id: 53, name: "Matthijs de Ligt", position: 14 },
        { id: 1, name: "Lionel Messi", position: 15 },
        { id: 2, name: "Cristiano Ronaldo", position: 16 },
        { id: 33, name: "Frenkie de Jong", position: 17 },
        { id: 34, name: "Federico Valverde", position: 18 },
        { id: 35, name: "Jamal Musiala", position: 19 },
        { id: 3, name: "Kylian Mbappé", position: 20 },
        { id: 4, name: "Erling Haaland", position: 21 },
        { id: 54, name: "Alphonso Davies", position: 22 },
        { id: 55, name: "Kyle Walker", position: 23 },
        { id: 5, name: "Neymar", position: 24 },
        { id: 36, name: "Lamine Yamal", position: 25 },
        { id: 56, name: "Dayot Upamecano", position: 26 },
        { id: 6, name: "Mohamed Salah", position: 27 },
        { id: 37, name: "Enzo Fernández", position: 28 },
        { id: 57, name: "Éder Militão", position: 29 }
    ],
    3: [
        { id: 7, name: "Vinícius Júnior", position: 0 },
        { id: 8, name: "Harry Kane", position: 1 },
        { id: 9, name: "Sadio Mané", position: 2 },
        { id: 10, name: "Son Heung-min", position: 3 },
        { id: 11, name: "Robert Lewandowski", position: 4 },
        { id: 12, name: "Victor Osimhen", position: 5 },
        { id: 38, name: "Eduardo Camavinga", position: 6 },
        { id: 39, name: "Florian Wirtz", position: 7 },
        { id: 40, name: "James Maddison", position: 8 },
        { id: 58, name: "Reece James", position: 9 },
        { id: 59, name: "Ben White", position: 10 },
        { id: 60, name: "John Stones", position: 11 },
        { id: 61, name: "Jurrien Timber", position: 12 },
        { id: 62, name: "Cole Palmer", position: 13 },
        { id: 63, name: "Bruno Guimarães", position: 14 },
        { id: 13, name: "Antoine Griezmann", position: 15 },
        { id: 14, name: "Lautaro Martínez", position: 16 },
        { id: 15, name: "Julián Álvarez", position: 17 },
        { id: 16, name: "Viktor Gyökeres", position: 18 },
        { id: 17, name: "Bukayo Saka", position: 19 },
        { id: 64, name: "Jarrod Bowen", position: 20 },
        { id: 65, name: "Dominik Szoboszlai", position: 21 },
        { id: 21, name: "Kevin De Bruyne", position: 22 },
        { id: 22, name: "Jude Bellingham", position: 23 },
        { id: 23, name: "Pedri", position: 24 },
        { id: 24, name: "Rodri", position: 25 },
        { id: 18, name: "Khvicha Kvaratskhelia", position: 26 },
        { id: 19, name: "Marcus Rashford", position: 27 },
        { id: 20, name: "Rafael Leão", position: 28 },
        { id: 25, name: "Phil Foden", position: 29 }
    ],
    4: [
        { id: 41, name: "Virgil van Dijk", position: 0 },
        { id: 42, name: "Sergio Ramos", position: 1 },
        { id: 43, name: "Antonio Rüdiger", position: 2 },
        { id: 44, name: "Rúben Dias", position: 3 },
        { id: 45, name: "Marquinhos", position: 4 },
        { id: 26, name: "Bernardo Silva", position: 5 },
        { id: 27, name: "Luka Modrić", position: 6 },
        { id: 28, name: "Toni Kroos", position: 7 },
        { id: 29, name: "Joshua Kimmich", position: 8 },
        { id: 30, name: "Declan Rice", position: 9 },
        { id: 46, name: "João Cancelo", position: 10 },
        { id: 47, name: "Trent Alexander-Arnold", position: 11 },
        { id: 48, name: "Achraf Hakimi", position: 12 },
        { id: 49, name: "Theo Hernández", position: 13 },
        { id: 50, name: "Jules Koundé", position: 14 },
        { id: 1, name: "Lionel Messi", position: 15 },
        { id: 2, name: "Cristiano Ronaldo", position: 16 },
        { id: 3, name: "Kylian Mbappé", position: 17 },
        { id: 31, name: "Martin Ødegaard", position: 18 },
        { id: 32, name: "Bruno Fernandes", position: 19 },
        { id: 4, name: "Erling Haaland", position: 20 },
        { id: 5, name: "Neymar", position: 21 },
        { id: 51, name: "William Saliba", position: 22 },
        { id: 52, name: "Gabriel Magalhães", position: 23 },
        { id: 6, name: "Mohamed Salah", position: 24 },
        { id: 33, name: "Frenkie de Jong", position: 25 },
        { id: 7, name: "Vinícius Júnior", position: 26 },
        { id: 34, name: "Federico Valverde", position: 27 },
        { id: 8, name: "Harry Kane", position: 28 },
        { id: 35, name: "Jamal Musiala", position: 29 }
    ],
    5: [
        { id: 9, name: "Sadio Mané", position: 0 },
        { id: 10, name: "Son Heung-min", position: 1 },
        { id: 11, name: "Robert Lewandowski", position: 2 },
        { id: 12, name: "Victor Osimhen", position: 3 },
        { id: 13, name: "Antoine Griezmann", position: 4 },
        { id: 14, name: "Lautaro Martínez", position: 5 },
        { id: 15, name: "Julián Álvarez", position: 6 },
        { id: 16, name: "Viktor Gyökeres", position: 7 },
        { id: 53, name: "Matthijs de Ligt", position: 8 },
        { id: 54, name: "Alphonso Davies", position: 9 },
        { id: 55, name: "Kyle Walker", position: 10 },
        { id: 56, name: "Dayot Upamecano", position: 11 },
        { id: 57, name: "Éder Militão", position: 12 },
        { id: 58, name: "Reece James", position: 13 },
        { id: 59, name: "Ben White", position: 14 },
        { id: 17, name: "Bukayo Saka", position: 15 },
        { id: 18, name: "Khvicha Kvaratskhelia", position: 16 },
        { id: 19, name: "Marcus Rashford", position: 17 },
        { id: 20, name: "Rafael Leão", position: 18 },
        { id: 36, name: "Lamine Yamal", position: 19 },
        { id: 60, name: "John Stones", position: 20 },
        { id: 61, name: "Jurrien Timber", position: 21 },
        { id: 62, name: "Cole Palmer", position: 22 },
        { id: 63, name: "Bruno Guimarães", position: 23 },
        { id: 37, name: "Enzo Fernández", position: 24 },
        { id: 38, name: "Eduardo Camavinga", position: 25 },
        { id: 64, name: "Jarrod Bowen", position: 26 },
        { id: 65, name: "Dominik Szoboszlai", position: 27 },
        { id: 39, name: "Florian Wirtz", position: 28 },
        { id: 40, name: "James Maddison", position: 29 }
    ],
    6: [
        { id: 21, name: "Kevin De Bruyne", position: 0 },
        { id: 22, name: "Jude Bellingham", position: 1 },
        { id: 23, name: "Pedri", position: 2 },
        { id: 24, name: "Rodri", position: 3 },
        { id: 25, name: "Phil Foden", position: 4 },
        { id: 1, name: "Lionel Messi", position: 5 },
        { id: 2, name: "Cristiano Ronaldo", position: 6 },
        { id: 26, name: "Bernardo Silva", position: 7 },
        { id: 27, name: "Luka Modrić", position: 8 },
        { id: 28, name: "Toni Kroos", position: 9 },
        { id: 3, name: "Kylian Mbappé", position: 10 },
        { id: 4, name: "Erling Haaland", position: 11 },
        { id: 41, name: "Virgil van Dijk", position: 12 },
        { id: 42, name: "Sergio Ramos", position: 13 },
        { id: 43, name: "Antonio Rüdiger", position: 14 },
        { id: 5, name: "Neymar", position: 15 },
        { id: 6, name: "Mohamed Salah", position: 16 },
        { id: 29, name: "Joshua Kimmich", position: 17 },
        { id: 30, name: "Declan Rice", position: 18 },
        { id: 44, name: "Rúben Dias", position: 19 },
        { id: 7, name: "Vinícius Júnior", position: 20 },
        { id: 8, name: "Harry Kane", position: 21 },
        { id: 45, name: "Marquinhos", position: 22 },
        { id: 46, name: "João Cancelo", position: 23 },
        { id: 9, name: "Sadio Mané", position: 24 },
        { id: 10, name: "Son Heung-min", position: 25 },
        { id: 47, name: "Trent Alexander-Arnold", position: 26 },
        { id: 48, name: "Achraf Hakimi", position: 27 },
        { id: 11, name: "Robert Lewandowski", position: 28 },
        { id: 12, name: "Victor Osimhen", position: 29 }
    ],
    7: [
        { id: 13, name: "Antoine Griezmann", position: 0 },
        { id: 14, name: "Lautaro Martínez", position: 1 },
        { id: 15, name: "Julián Álvarez", position: 2 },
        { id: 16, name: "Viktor Gyökeres", position: 3 },
        { id: 17, name: "Bukayo Saka", position: 4 },
        { id: 18, name: "Khvicha Kvaratskhelia", position: 5 },
        { id: 49, name: "Theo Hernández", position: 6 },
        { id: 50, name: "Jules Koundé", position: 7 },
        { id: 51, name: "William Saliba", position: 8 },
        { id: 52, name: "Gabriel Magalhães", position: 9 },
        { id: 19, name: "Marcus Rashford", position: 10 },
        { id: 20, name: "Rafael Leão", position: 11 },
        { id: 31, name: "Martin Ødegaard", position: 12 },
        { id: 32, name: "Bruno Fernandes", position: 13 },
        { id: 33, name: "Frenkie de Jong", position: 14 },
        { id: 53, name: "Matthijs de Ligt", position: 15 },
        { id: 54, name: "Alphonso Davies", position: 16 },
        { id: 55, name: "Kyle Walker", position: 17 },
        { id: 34, name: "Federico Valverde", position: 18 },
        { id: 35, name: "Jamal Musiala", position: 19 },
        { id: 56, name: "Dayot Upamecano", position: 20 },
        { id: 57, name: "Éder Militão", position: 21 },
        { id: 58, name: "Reece James", position: 22 },
        { id: 59, name: "Ben White", position: 23 },
        { id: 36, name: "Lamine Yamal", position: 24 },
        { id: 37, name: "Enzo Fernández", position: 25 },
        { id: 60, name: "John Stones", position: 26 },
        { id: 61, name: "Jurrien Timber", position: 27 },
        { id: 38, name: "Eduardo Camavinga", position: 28 },
        { id: 39, name: "Florian Wirtz", position: 29 }
    ],
    8: [
        { id: 62, name: "Cole Palmer", position: 0 },
        { id: 63, name: "Bruno Guimarães", position: 1 },
        { id: 64, name: "Jarrod Bowen", position: 2 },
        { id: 65, name: "Dominik Szoboszlai", position: 3 },
        { id: 40, name: "James Maddison", position: 4 },
        { id: 1, name: "Lionel Messi", position: 5 },
        { id: 21, name: "Kevin De Bruyne", position: 6 },
        { id: 22, name: "Jude Bellingham", position: 7 },
        { id: 2, name: "Cristiano Ronaldo", position: 8 },
        { id: 23, name: "Pedri", position: 9 },
        { id: 3, name: "Kylian Mbappé", position: 10 },
        { id: 24, name: "Rodri", position: 11 },
        { id: 4, name: "Erling Haaland", position: 12 },
        { id: 25, name: "Phil Foden", position: 13 },
        { id: 5, name: "Neymar", position: 14 },
        { id: 41, name: "Virgil van Dijk", position: 15 },
        { id: 6, name: "Mohamed Salah", position: 16 },
        { id: 42, name: "Sergio Ramos", position: 17 },
        { id: 7, name: "Vinícius Júnior", position: 18 },
        { id: 43, name: "Antonio Rüdiger", position: 19 },
        { id: 8, name: "Harry Kane", position: 20 },
        { id: 44, name: "Rúben Dias", position: 21 },
        { id: 9, name: "Sadio Mané", position: 22 },
        { id: 45, name: "Marquinhos", position: 23 },
        { id: 10, name: "Son Heung-min", position: 24 },
        { id: 46, name: "João Cancelo", position: 25 },
        { id: 11, name: "Robert Lewandowski", position: 26 },
        { id: 47, name: "Trent Alexander-Arnold", position: 27 },
        { id: 12, name: "Victor Osimhen", position: 28 },
        { id: 48, name: "Achraf Hakimi", position: 29 }
    ],
    9: [
        { id: 26, name: "Bernardo Silva", position: 0 },
        { id: 27, name: "Luka Modrić", position: 1 },
        { id: 28, name: "Toni Kroos", position: 2 },
        { id: 29, name: "Joshua Kimmich", position: 3 },
        { id: 30, name: "Declan Rice", position: 4 },
        { id: 13, name: "Antoine Griezmann", position: 5 },
        { id: 49, name: "Theo Hernández", position: 6 },
        { id: 14, name: "Lautaro Martínez", position: 7 },
        { id: 50, name: "Jules Koundé", position: 8 },
        { id: 15, name: "Julián Álvarez", position: 9 },
        { id: 51, name: "William Saliba", position: 10 },
        { id: 16, name: "Viktor Gyökeres", position: 11 },
        { id: 52, name: "Gabriel Magalhães", position: 12 },
        { id: 17, name: "Bukayo Saka", position: 13 },
        { id: 53, name: "Matthijs de Ligt", position: 14 },
        { id: 18, name: "Khvicha Kvaratskhelia", position: 15 },
        { id: 54, name: "Alphonso Davies", position: 16 },
        { id: 19, name: "Marcus Rashford", position: 17 },
        { id: 55, name: "Kyle Walker", position: 18 },
        { id: 20, name: "Rafael Leão", position: 19 },
        { id: 56, name: "Dayot Upamecano", position: 20 },
        { id: 31, name: "Martin Ødegaard", position: 21 },
        { id: 57, name: "Éder Militão", position: 22 },
        { id: 32, name: "Bruno Fernandes", position: 23 },
        { id: 58, name: "Reece James", position: 24 },
        { id: 33, name: "Frenkie de Jong", position: 25 },
        { id: 59, name: "Ben White", position: 26 },
        { id: 34, name: "Federico Valverde", position: 27 },
        { id: 60, name: "John Stones", position: 28 },
        { id: 35, name: "Jamal Musiala", position: 29 }
    ],
    10: [
        { id: 36, name: "Lamine Yamal", position: 0 },
        { id: 61, name: "Jurrien Timber", position: 1 },
        { id: 37, name: "Enzo Fernández", position: 2 },
        { id: 62, name: "Cole Palmer", position: 3 },
        { id: 38, name: "Eduardo Camavinga", position: 4 },
        { id: 63, name: "Bruno Guimarães", position: 5 },
        { id: 39, name: "Florian Wirtz", position: 6 },
        { id: 64, name: "Jarrod Bowen", position: 7 },
        { id: 40, name: "James Maddison", position: 8 },
        { id: 65, name: "Dominik Szoboszlai", position: 9 },
        { id: 1, name: "Lionel Messi", position: 10 },
        { id: 41, name: "Virgil van Dijk", position: 11 },
        { id: 2, name: "Cristiano Ronaldo", position: 12 },
        { id: 42, name: "Sergio Ramos", position: 13 },
        { id: 3, name: "Kylian Mbappé", position: 14 },
        { id: 21, name: "Kevin De Bruyne", position: 15 },
        { id: 4, name: "Erling Haaland", position: 16 },
        { id: 22, name: "Jude Bellingham", position: 17 },
        { id: 5, name: "Neymar", position: 18 },
        { id: 23, name: "Pedri", position: 19 },
        { id: 6, name: "Mohamed Salah", position: 20 },
        { id: 24, name: "Rodri", position: 21 },
        { id: 7, name: "Vinícius Júnior", position: 22 },
        { id: 25, name: "Phil Foden", position: 23 },
        { id: 8, name: "Harry Kane", position: 24 },
        { id: 43, name: "Antonio Rüdiger", position: 25 },
        { id: 9, name: "Sadio Mané", position: 26 },
        { id: 44, name: "Rúben Dias", position: 27 },
        { id: 10, name: "Son Heung-min", position: 28 },
        { id: 45, name: "Marquinhos", position: 29 }
    ],
    11: [
        { id: 11, name: "Robert Lewandowski", position: 0 },
        { id: 46, name: "João Cancelo", position: 1 },
        { id: 12, name: "Victor Osimhen", position: 2 },
        { id: 47, name: "Trent Alexander-Arnold", position: 3 },
        { id: 13, name: "Antoine Griezmann", position: 4 },
        { id: 48, name: "Achraf Hakimi", position: 5 },
        { id: 14, name: "Lautaro Martínez", position: 6 },
        { id: 49, name: "Theo Hernández", position: 7 },
        { id: 15, name: "Julián Álvarez", position: 8 },
        { id: 50, name: "Jules Koundé", position: 9 },
        { id: 16, name: "Viktor Gyökeres", position: 10 },
        { id: 51, name: "William Saliba", position: 11 },
        { id: 17, name: "Bukayo Saka", position: 12 },
        { id: 52, name: "Gabriel Magalhães", position: 13 },
        { id: 18, name: "Khvicha Kvaratskhelia", position: 14 },
        { id: 53, name: "Matthijs de Ligt", position: 15 },
        { id: 19, name: "Marcus Rashford", position: 16 },
        { id: 54, name: "Alphonso Davies", position: 17 },
        { id: 20, name: "Rafael Leão", position: 18 },
        { id: 55, name: "Kyle Walker", position: 19 },
        { id: 26, name: "Bernardo Silva", position: 20 },
        { id: 56, name: "Dayot Upamecano", position: 21 },
        { id: 27, name: "Luka Modrić", position: 22 },
        { id: 57, name: "Éder Militão", position: 23 },
        { id: 28, name: "Toni Kroos", position: 24 },
        { id: 58, name: "Reece James", position: 25 },
        { id: 29, name: "Joshua Kimmich", position: 26 },
        { id: 59, name: "Ben White", position: 27 },
        { id: 30, name: "Declan Rice", position: 28 },
        { id: 60, name: "John Stones", position: 29 }
    ],
    12: [
        { id: 31, name: "Martin Ødegaard", position: 0 },
        { id: 61, name: "Jurrien Timber", position: 1 },
        { id: 32, name: "Bruno Fernandes", position: 2 },
        { id: 62, name: "Cole Palmer", position: 3 },
        { id: 33, name: "Frenkie de Jong", position: 4 },
        { id: 63, name: "Bruno Guimarães", position: 5 },
        { id: 34, name: "Federico Valverde", position: 6 },
        { id: 64, name: "Jarrod Bowen", position: 7 },
        { id: 35, name: "Jamal Musiala", position: 8 },
        { id: 65, name: "Dominik Szoboszlai", position: 9 },
        { id: 36, name: "Lamine Yamal", position: 10 },
        { id: 1, name: "Lionel Messi", position: 11 },
        { id: 37, name: "Enzo Fernández", position: 12 },
        { id: 2, name: "Cristiano Ronaldo", position: 13 },
        { id: 38, name: "Eduardo Camavinga", position: 14 },
        { id: 3, name: "Kylian Mbappé", position: 15 },
        { id: 39, name: "Florian Wirtz", position: 16 },
        { id: 4, name: "Erling Haaland", position: 17 },
        { id: 40, name: "James Maddison", position: 18 },
        { id: 5, name: "Neymar", position: 19 },
        { id: 41, name: "Virgil van Dijk", position: 20 },
        { id: 6, name: "Mohamed Salah", position: 21 },
        { id: 42, name: "Sergio Ramos", position: 22 },
        { id: 7, name: "Vinícius Júnior", position: 23 },
        { id: 43, name: "Antonio Rüdiger", position: 24 },
        { id: 8, name: "Harry Kane", position: 25 },
        { id: 44, name: "Rúben Dias", position: 26 },
        { id: 9, name: "Sadio Mané", position: 27 },
        { id: 45, name: "Marquinhos", position: 28 },
        { id: 10, name: "Son Heung-min", position: 29 }
    ],
    13: [
        { id: 11, name: "Robert Lewandowski", position: 0 },
        { id: 46, name: "João Cancelo", position: 1 },
        { id: 12, name: "Victor Osimhen", position: 2 },
        { id: 47, name: "Trent Alexander-Arnold", position: 3 },
        { id: 13, name: "Antoine Griezmann", position: 4 },
        { id: 48, name: "Achraf Hakimi", position: 5 },
        { id: 14, name: "Lautaro Martínez", position: 6 },
        { id: 49, name: "Theo Hernández", position: 7 },
        { id: 15, name: "Julián Álvarez", position: 8 },
        { id: 50, name: "Jules Koundé", position: 9 },
        { id: 16, name: "Viktor Gyökeres", position: 10 },
        { id: 51, name: "William Saliba", position: 11 },
        { id: 17, name: "Bukayo Saka", position: 12 },
        { id: 21, name: "Kevin De Bruyne", position: 13 },
        { id: 18, name: "Khvicha Kvaratskhelia", position: 14 },
        { id: 22, name: "Jude Bellingham", position: 15 },
        { id: 19, name: "Marcus Rashford", position: 16 },
        { id: 23, name: "Pedri", position: 17 },
        { id: 20, name: "Rafael Leão", position: 18 },
        { id: 24, name: "Rodri", position: 19 },
        { id: 52, name: "Gabriel Magalhães", position: 20 },
        { id: 25, name: "Phil Foden", position: 21 },
        { id: 53, name: "Matthijs de Ligt", position: 22 },
        { id: 26, name: "Bernardo Silva", position: 23 },
        { id: 54, name: "Alphonso Davies", position: 24 },
        { id: 27, name: "Luka Modrić", position: 25 },
        { id: 55, name: "Kyle Walker", position: 26 },
        { id: 28, name: "Toni Kroos", position: 27 },
        { id: 56, name: "Dayot Upamecano", position: 28 },
        { id: 29, name: "Joshua Kimmich", position: 29 }
    ],
    14: [
        { id: 30, name: "Declan Rice", position: 0 },
        { id: 57, name: "Éder Militão", position: 1 },
        { id: 31, name: "Martin Ødegaard", position: 2 },
        { id: 58, name: "Reece James", position: 3 },
        { id: 32, name: "Bruno Fernandes", position: 4 },
        { id: 59, name: "Ben White", position: 5 },
        { id: 33, name: "Frenkie de Jong", position: 6 },
        { id: 60, name: "John Stones", position: 7 },
        { id: 34, name: "Federico Valverde", position: 8 },
        { id: 61, name: "Jurrien Timber", position: 9 },
        { id: 35, name: "Jamal Musiala", position: 10 },
        { id: 1, name: "Lionel Messi", position: 11 },
        { id: 36, name: "Lamine Yamal", position: 12 },
        { id: 2, name: "Cristiano Ronaldo", position: 13 },
        { id: 37, name: "Enzo Fernández", position: 14 },
        { id: 3, name: "Kylian Mbappé", position: 15 },
        { id: 38, name: "Eduardo Camavinga", position: 16 },
        { id: 4, name: "Erling Haaland", position: 17 },
        { id: 39, name: "Florian Wirtz", position: 18 },
        { id: 5, name: "Neymar", position: 19 },
        { id: 40, name: "James Maddison", position: 20 },
        { id: 41, name: "Virgil van Dijk", position: 21 },
        { id: 6, name: "Mohamed Salah", position: 22 },
        { id: 62, name: "Cole Palmer", position: 23 },
        { id: 7, name: "Vinícius Júnior", position: 24 },
        { id: 63, name: "Bruno Guimarães", position: 25 },
        { id: 8, name: "Harry Kane", position: 26 },
        { id: 64, name: "Jarrod Bowen", position: 27 },
        { id: 42, name: "Sergio Ramos", position: 28 },
        { id: 65, name: "Dominik Szoboszlai", position: 29 }
    ],
    15: [
        { id: 9, name: "Sadio Mané", position: 0 },
        { id: 43, name: "Antonio Rüdiger", position: 1 },
        { id: 10, name: "Son Heung-min", position: 2 },
        { id: 44, name: "Rúben Dias", position: 3 },
        { id: 11, name: "Robert Lewandowski", position: 4 },
        { id: 45, name: "Marquinhos", position: 5 },
        { id: 12, name: "Victor Osimhen", position: 6 },
        { id: 46, name: "João Cancelo", position: 7 },
        { id: 13, name: "Antoine Griezmann", position: 8 },
        { id: 47, name: "Trent Alexander-Arnold", position: 9 },
        { id: 14, name: "Lautaro Martínez", position: 10 },
        { id: 48, name: "Achraf Hakimi", position: 11 },
        { id: 15, name: "Julián Álvarez", position: 12 },
        { id: 49, name: "Theo Hernández", position: 13 },
        { id: 16, name: "Viktor Gyökeres", position: 14 },
        { id: 50, name: "Jules Koundé", position: 15 },
        { id: 17, name: "Bukayo Saka", position: 16 },
        { id: 51, name: "William Saliba", position: 17 },
        { id: 18, name: "Khvicha Kvaratskhelia", position: 18 },
        { id: 52, name: "Gabriel Magalhães", position: 19 },
        { id: 19, name: "Marcus Rashford", position: 20 },
        { id: 53, name: "Matthijs de Ligt", position: 21 },
        { id: 20, name: "Rafael Leão", position: 22 },
        { id: 54, name: "Alphonso Davies", position: 23 },
        { id: 21, name: "Kevin De Bruyne", position: 24 },
        { id: 55, name: "Kyle Walker", position: 25 },
        { id: 22, name: "Jude Bellingham", position: 26 },
        { id: 56, name: "Dayot Upamecano", position: 27 },
        { id: 23, name: "Pedri", position: 28 },
        { id: 57, name: "Éder Militão", position: 29 }
    ],
    16: [
        { id: 24, name: "Rodri", position: 0 },
        { id: 58, name: "Reece James", position: 1 },
        { id: 25, name: "Phil Foden", position: 2 },
        { id: 59, name: "Ben White", position: 3 },
        { id: 26, name: "Bernardo Silva", position: 4 },
        { id: 60, name: "John Stones", position: 5 },
        { id: 27, name: "Luka Modrić", position: 6 },
        { id: 61, name: "Jurrien Timber", position: 7 },
        { id: 28, name: "Toni Kroos", position: 8 },
        { id: 62, name: "Cole Palmer", position: 9 },
        { id: 29, name: "Joshua Kimmich", position: 10 },
        { id: 63, name: "Bruno Guimarães", position: 11 },
        { id: 30, name: "Declan Rice", position: 12 },
        { id: 64, name: "Jarrod Bowen", position: 13 },
        { id: 31, name: "Martin Ødegaard", position: 14 },
        { id: 65, name: "Dominik Szoboszlai", position: 15 },
        { id: 32, name: "Bruno Fernandes", position: 16 },
        { id: 1, name: "Lionel Messi", position: 17 },
        { id: 33, name: "Frenkie de Jong", position: 18 },
        { id: 2, name: "Cristiano Ronaldo", position: 19 },
        { id: 34, name: "Federico Valverde", position: 20 },
        { id: 3, name: "Kylian Mbappé", position: 21 },
        { id: 35, name: "Jamal Musiala", position: 22 },
        { id: 4, name: "Erling Haaland", position: 23 },
        { id: 36, name: "Lamine Yamal", position: 24 },
        { id: 5, name: "Neymar", position: 25 },
        { id: 37, name: "Enzo Fernández", position: 26 },
        { id: 6, name: "Mohamed Salah", position: 27 },
        { id: 38, name: "Eduardo Camavinga", position: 28 },
        { id: 39, name: "Florian Wirtz", position: 29 }
    ],
    17: [
        { id: 40, name: "James Maddison", position: 0 },
        { id: 7, name: "Vinícius Júnior", position: 1 },
        { id: 41, name: "Virgil van Dijk", position: 2 },
        { id: 8, name: "Harry Kane", position: 3 },
        { id: 42, name: "Sergio Ramos", position: 4 },
        { id: 9, name: "Sadio Mané", position: 5 },
        { id: 43, name: "Antonio Rüdiger", position: 6 },
        { id: 10, name: "Son Heung-min", position: 7 },
        { id: 44, name: "Rúben Dias", position: 8 },
        { id: 11, name: "Robert Lewandowski", position: 9 },
        { id: 45, name: "Marquinhos", position: 10 },
        { id: 12, name: "Victor Osimhen", position: 11 },
        { id: 46, name: "João Cancelo", position: 12 },
        { id: 13, name: "Antoine Griezmann", position: 13 },
        { id: 47, name: "Trent Alexander-Arnold", position: 14 },
        { id: 14, name: "Lautaro Martínez", position: 15 },
        { id: 48, name: "Achraf Hakimi", position: 16 },
        { id: 15, name: "Julián Álvarez", position: 17 },
        { id: 49, name: "Theo Hernández", position: 18 },
        { id: 16, name: "Viktor Gyökeres", position: 19 },
        { id: 50, name: "Jules Koundé", position: 20 },
        { id: 17, name: "Bukayo Saka", position: 21 },
        { id: 51, name: "William Saliba", position: 22 },
        { id: 18, name: "Khvicha Kvaratskhelia", position: 23 },
        { id: 52, name: "Gabriel Magalhães", position: 24 },
        { id: 19, name: "Marcus Rashford", position: 25 },
        { id: 53, name: "Matthijs de Ligt", position: 26 },
        { id: 20, name: "Rafael Leão", position: 27 },
        { id: 54, name: "Alphonso Davies", position: 28 },
        { id: 55, name: "Kyle Walker", position: 29 }
    ],
    18: [
        { id: 56, name: "Dayot Upamecano", position: 0 },
        { id: 21, name: "Kevin De Bruyne", position: 1 },
        { id: 57, name: "Éder Militão", position: 2 },
        { id: 22, name: "Jude Bellingham", position: 3 },
        { id: 58, name: "Reece James", position: 4 },
        { id: 23, name: "Pedri", position: 5 },
        { id: 59, name: "Ben White", position: 6 },
        { id: 24, name: "Rodri", position: 7 },
        { id: 60, name: "John Stones", position: 8 },
        { id: 25, name: "Phil Foden", position: 9 },
        { id: 61, name: "Jurrien Timber", position: 10 },
        { id: 26, name: "Bernardo Silva", position: 11 },
        { id: 62, name: "Cole Palmer", position: 12 },
        { id: 27, name: "Luka Modrić", position: 13 },
        { id: 63, name: "Bruno Guimarães", position: 14 },
        { id: 28, name: "Toni Kroos", position: 15 },
        { id: 64, name: "Jarrod Bowen", position: 16 },
        { id: 29, name: "Joshua Kimmich", position: 17 },
        { id: 65, name: "Dominik Szoboszlai", position: 18 },
        { id: 30, name: "Declan Rice", position: 19 },
        { id: 1, name: "Lionel Messi", position: 20 },
        { id: 31, name: "Martin Ødegaard", position: 21 },
        { id: 2, name: "Cristiano Ronaldo", position: 22 },
        { id: 32, name: "Bruno Fernandes", position: 23 },
        { id: 3, name: "Kylian Mbappé", position: 24 },
        { id: 33, name: "Frenkie de Jong", position: 25 },
        { id: 4, name: "Erling Haaland", position: 26 },
        { id: 34, name: "Federico Valverde", position: 27 },
        { id: 5, name: "Neymar", position: 28 },
        { id: 35, name: "Jamal Musiala", position: 29 }
    ],
    19: [
        { id: 36, name: "Lamine Yamal", position: 0 },
        { id: 6, name: "Mohamed Salah", position: 1 },
        { id: 37, name: "Enzo Fernández", position: 2 },
        { id: 7, name: "Vinícius Júnior", position: 3 },
        { id: 38, name: "Eduardo Camavinga", position: 4 },
        { id: 8, name: "Harry Kane", position: 5 },
        { id: 39, name: "Florian Wirtz", position: 6 },
        { id: 40, name: "James Maddison", position: 7 },
        { id: 41, name: "Virgil van Dijk", position: 8 },
        { id: 9, name: "Sadio Mané", position: 9 },
        { id: 42, name: "Sergio Ramos", position: 10 },
        { id: 10, name: "Son Heung-min", position: 11 },
        { id: 43, name: "Antonio Rüdiger", position: 12 },
        { id: 11, name: "Robert Lewandowski", position: 13 },
        { id: 44, name: "Rúben Dias", position: 14 },
        { id: 12, name: "Victor Osimhen", position: 15 },
        { id: 45, name: "Marquinhos", position: 16 },
        { id: 46, name: "João Cancelo", position: 17 },
        { id: 47, name: "Trent Alexander-Arnold", position: 18 },
        { id: 48, name: "Achraf Hakimi", position: 19 },
        { id: 13, name: "Antoine Griezmann", position: 20 },
        { id: 49, name: "Theo Hernández", position: 21 },
        { id: 14, name: "Lautaro Martínez", position: 22 },
        { id: 50, name: "Jules Koundé", position: 23 },
        { id: 15, name: "Julián Álvarez", position: 24 },
        { id: 51, name: "William Saliba", position: 25 },
        { id: 16, name: "Viktor Gyökeres", position: 26 },
        { id: 52, name: "Gabriel Magalhães", position: 27 },
        { id: 17, name: "Bukayo Saka", position: 28 },
        { id: 53, name: "Matthijs de Ligt", position: 29 }
    ],
    20: [
        { id: 18, name: "Khvicha Kvaratskhelia", position: 0 },
        { id: 54, name: "Alphonso Davies", position: 1 },
        { id: 19, name: "Marcus Rashford", position: 2 },
        { id: 55, name: "Kyle Walker", position: 3 },
        { id: 20, name: "Rafael Leão", position: 4 },
        { id: 56, name: "Dayot Upamecano", position: 5 },
        { id: 21, name: "Kevin De Bruyne", position: 6 },
        { id: 57, name: "Éder Militão", position: 7 },
        { id: 22, name: "Jude Bellingham", position: 8 },
        { id: 58, name: "Reece James", position: 9 },
        { id: 23, name: "Pedri", position: 10 },
        { id: 59, name: "Ben White", position: 11 },
        { id: 24, name: "Rodri", position: 12 },
        { id: 60, name: "John Stones", position: 13 },
        { id: 25, name: "Phil Foden", position: 14 },
        { id: 61, name: "Jurrien Timber", position: 15 },
        { id: 26, name: "Bernardo Silva", position: 16 },
        { id: 62, name: "Cole Palmer", position: 17 },
        { id: 27, name: "Luka Modrić", position: 18 },
        { id: 63, name: "Bruno Guimarães", position: 19 },
        { id: 28, name: "Toni Kroos", position: 20 },
        { id: 64, name: "Jarrod Bowen", position: 21 },
        { id: 29, name: "Joshua Kimmich", position: 22 },
        { id: 65, name: "Dominik Szoboszlai", position: 23 },
        { id: 30, name: "Declan Rice", position: 24 },
        { id: 1, name: "Lionel Messi", position: 25 },
        { id: 31, name: "Martin Ødegaard", position: 26 },
        { id: 2, name: "Cristiano Ronaldo", position: 27 },
        { id: 32, name: "Bruno Fernandes", position: 28 },
        { id: 33, name: "Frenkie de Jong", position: 29 }
    ],
    21: [
        { id: 34, name: "Federico Valverde", position: 0 },
        { id: 3, name: "Kylian Mbappé", position: 1 },
        { id: 35, name: "Jamal Musiala", position: 2 },
        { id: 4, name: "Erling Haaland", position: 3 },
        { id: 36, name: "Lamine Yamal", position: 4 },
        { id: 5, name: "Neymar", position: 5 },
        { id: 37, name: "Enzo Fernández", position: 6 },
        { id: 6, name: "Mohamed Salah", position: 7 },
        { id: 38, name: "Eduardo Camavinga", position: 8 },
        { id: 7, name: "Vinícius Júnior", position: 9 },
        { id: 39, name: "Florian Wirtz", position: 10 },
        { id: 8, name: "Harry Kane", position: 11 },
        { id: 40, name: "James Maddison", position: 12 },
        { id: 41, name: "Virgil van Dijk", position: 13 },
        { id: 9, name: "Sadio Mané", position: 14 },
        { id: 42, name: "Sergio Ramos", position: 15 },
        { id: 10, name: "Son Heung-min", position: 16 },
        { id: 43, name: "Antonio Rüdiger", position: 17 },
        { id: 11, name: "Robert Lewandowski", position: 18 },
        { id: 44, name: "Rúben Dias", position: 19 },
        { id: 12, name: "Victor Osimhen", position: 20 },
        { id: 45, name: "Marquinhos", position: 21 },
        { id: 46, name: "João Cancelo", position: 22 },
        { id: 47, name: "Trent Alexander-Arnold", position: 23 },
        { id: 48, name: "Achraf Hakimi", position: 24 },
        { id: 13, name: "Antoine Griezmann", position: 25 },
        { id: 49, name: "Theo Hernández", position: 26 },
        { id: 14, name: "Lautaro Martínez", position: 27 },
        { id: 50, name: "Jules Koundé", position: 28 },
        { id: 15, name: "Julián Álvarez", position: 29 }
    ],
    22: [
        { id: 51, name: "William Saliba", position: 0 },
        { id: 16, name: "Viktor Gyökeres", position: 1 },
        { id: 52, name: "Gabriel Magalhães", position: 2 },
        { id: 17, name: "Bukayo Saka", position: 3 },
        { id: 53, name: "Matthijs de Ligt", position: 4 },
        { id: 18, name: "Khvicha Kvaratskhelia", position: 5 },
        { id: 54, name: "Alphonso Davies", position: 6 },
        { id: 19, name: "Marcus Rashford", position: 7 },
        { id: 55, name: "Kyle Walker", position: 8 },
        { id: 20, name: "Rafael Leão", position: 9 },
        { id: 56, name: "Dayot Upamecano", position: 10 },
        { id: 21, name: "Kevin De Bruyne", position: 11 },
        { id: 57, name: "Éder Militão", position: 12 },
        { id: 22, name: "Jude Bellingham", position: 13 },
        { id: 58, name: "Reece James", position: 14 },
        { id: 23, name: "Pedri", position: 15 },
        { id: 59, name: "Ben White", position: 16 },
        { id: 24, name: "Rodri", position: 17 },
        { id: 60, name: "John Stones", position: 18 },
        { id: 25, name: "Phil Foden", position: 19 },
        { id: 61, name: "Jurrien Timber", position: 20 },
        { id: 26, name: "Bernardo Silva", position: 21 },
        { id: 62, name: "Cole Palmer", position: 22 },
        { id: 27, name: "Luka Modrić", position: 23 },
        { id: 63, name: "Bruno Guimarães", position: 24 },
        { id: 28, name: "Toni Kroos", position: 25 },
        { id: 64, name: "Jarrod Bowen", position: 26 },
        { id: 29, name: "Joshua Kimmich", position: 27 },
        { id: 65, name: "Dominik Szoboszlai", position: 28 },
        { id: 30, name: "Declan Rice", position: 29 }
    ],
    23: [
        { id: 1, name: "Lionel Messi", position: 0 },
        { id: 31, name: "Martin Ødegaard", position: 1 },
        { id: 2, name: "Cristiano Ronaldo", position: 2 },
        { id: 32, name: "Bruno Fernandes", position: 3 },
        { id: 3, name: "Kylian Mbappé", position: 4 },
        { id: 33, name: "Frenkie de Jong", position: 5 },
        { id: 4, name: "Erling Haaland", position: 6 },
        { id: 34, name: "Federico Valverde", position: 7 },
        { id: 5, name: "Neymar", position: 8 },
        { id: 35, name: "Jamal Musiala", position: 9 },
        { id: 6, name: "Mohamed Salah", position: 10 },
        { id: 36, name: "Lamine Yamal", position: 11 },
        { id: 7, name: "Vinícius Júnior", position: 12 },
        { id: 37, name: "Enzo Fernández", position: 13 },
        { id: 8, name: "Harry Kane", position: 14 },
        { id: 38, name: "Eduardo Camavinga", position: 15 },
        { id: 9, name: "Sadio Mané", position: 16 },
        { id: 39, name: "Florian Wirtz", position: 17 },
        { id: 10, name: "Son Heung-min", position: 18 },
        { id: 40, name: "James Maddison", position: 19 },
        { id: 41, name: "Virgil van Dijk", position: 20 },
        { id: 11, name: "Robert Lewandowski", position: 21 },
        { id: 42, name: "Sergio Ramos", position: 22 },
        { id: 12, name: "Victor Osimhen", position: 23 },
        { id: 43, name: "Antonio Rüdiger", position: 24 },
        { id: 13, name: "Antoine Griezmann", position: 25 },
        { id: 44, name: "Rúben Dias", position: 26 },
        { id: 14, name: "Lautaro Martínez", position: 27 },
        { id: 45, name: "Marquinhos", position: 28 },
        { id: 15, name: "Julián Álvarez", position: 29 }
    ],
    24: [
        { id: 46, name: "João Cancelo", position: 0 },
        { id: 16, name: "Viktor Gyökeres", position: 1 },
        { id: 47, name: "Trent Alexander-Arnold", position: 2 },
        { id: 17, name: "Bukayo Saka", position: 3 },
        { id: 48, name: "Achraf Hakimi", position: 4 },
        { id: 18, name: "Khvicha Kvaratskhelia", position: 5 },
        { id: 49, name: "Theo Hernández", position: 6 },
        { id: 19, name: "Marcus Rashford", position: 7 },
        { id: 50, name: "Jules Koundé", position: 8 },
        { id: 20, name: "Rafael Leão", position: 9 },
        { id: 51, name: "William Saliba", position: 10 },
        { id: 21, name: "Kevin De Bruyne", position: 11 },
        { id: 52, name: "Gabriel Magalhães", position: 12 },
        { id: 22, name: "Jude Bellingham", position: 13 },
        { id: 53, name: "Matthijs de Ligt", position: 14 },
        { id: 23, name: "Pedri", position: 15 },
        { id: 54, name: "Alphonso Davies", position: 16 },
        { id: 24, name: "Rodri", position: 17 },
        { id: 55, name: "Kyle Walker", position: 18 },
        { id: 25, name: "Phil Foden", position: 19 },
        { id: 56, name: "Dayot Upamecano", position: 20 },
        { id: 26, name: "Bernardo Silva", position: 21 },
        { id: 57, name: "Éder Militão", position: 22 },
        { id: 27, name: "Luka Modrić", position: 23 },
        { id: 58, name: "Reece James", position: 24 },
        { id: 28, name: "Toni Kroos", position: 25 },
        { id: 59, name: "Ben White", position: 26 },
        { id: 29, name: "Joshua Kimmich", position: 27 },
        { id: 60, name: "John Stones", position: 28 },
        { id: 30, name: "Declan Rice", position: 29 }
    ],
    25: [
        { id: 61, name: "Jurrien Timber", position: 0 },
        { id: 31, name: "Martin Ødegaard", position: 1 },
        { id: 62, name: "Cole Palmer", position: 2 },
        { id: 32, name: "Bruno Fernandes", position: 3 },
        { id: 63, name: "Bruno Guimarães", position: 4 },
        { id: 33, name: "Frenkie de Jong", position: 5 },
        { id: 64, name: "Jarrod Bowen", position: 6 },
        { id: 34, name: "Federico Valverde", position: 7 },
        { id: 65, name: "Dominik Szoboszlai", position: 8 },
        { id: 35, name: "Jamal Musiala", position: 9 },
        { id: 1, name: "Lionel Messi", position: 10 },
        { id: 36, name: "Lamine Yamal", position: 11 },
        { id: 2, name: "Cristiano Ronaldo", position: 12 },
        { id: 37, name: "Enzo Fernández", position: 13 },
        { id: 3, name: "Kylian Mbappé", position: 14 },
        { id: 38, name: "Eduardo Camavinga", position: 15 },
        { id: 4, name: "Erling Haaland", position: 16 },
        { id: 39, name: "Florian Wirtz", position: 17 },
        { id: 5, name: "Neymar", position: 18 },
        { id: 40, name: "James Maddison", position: 19 },
        { id: 41, name: "Virgil van Dijk", position: 20 },
        { id: 6, name: "Mohamed Salah", position: 21 },
        { id: 42, name: "Sergio Ramos", position: 22 },
        { id: 7, name: "Vinícius Júnior", position: 23 },
        { id: 43, name: "Antonio Rüdiger", position: 24 },
        { id: 8, name: "Harry Kane", position: 25 },
        { id: 44, name: "Rúben Dias", position: 26 },
        { id: 9, name: "Sadio Mané", position: 27 },
        { id: 45, name: "Marquinhos", position: 28 },
        { id: 10, name: "Son Heung-min", position: 29 }
    ],
    26: [
        { id: 11, name: "Robert Lewandowski", position: 0 },
        { id: 46, name: "João Cancelo", position: 1 },
        { id: 12, name: "Victor Osimhen", position: 2 },
        { id: 47, name: "Trent Alexander-Arnold", position: 3 },
        { id: 13, name: "Antoine Griezmann", position: 4 },
        { id: 48, name: "Achraf Hakimi", position: 5 },
        { id: 14, name: "Lautaro Martínez", position: 6 },
        { id: 49, name: "Theo Hernández", position: 7 },
        { id: 15, name: "Julián Álvarez", position: 8 },
        { id: 50, name: "Jules Koundé", position: 9 },
        { id: 16, name: "Viktor Gyökeres", position: 10 },
        { id: 51, name: "William Saliba", position: 11 },
        { id: 17, name: "Bukayo Saka", position: 12 },
        { id: 52, name: "Gabriel Magalhães", position: 13 },
        { id: 18, name: "Khvicha Kvaratskhelia", position: 14 },
        { id: 53, name: "Matthijs de Ligt", position: 15 },
        { id: 19, name: "Marcus Rashford", position: 16 },
        { id: 54, name: "Alphonso Davies", position: 17 },
        { id: 20, name: "Rafael Leão", position: 18 },
        { id: 55, name: "Kyle Walker", position: 19 },
        { id: 21, name: "Kevin De Bruyne", position: 20 },
        { id: 56, name: "Dayot Upamecano", position: 21 },
        { id: 22, name: "Jude Bellingham", position: 22 },
        { id: 57, name: "Éder Militão", position: 23 },
        { id: 23, name: "Pedri", position: 24 },
        { id: 58, name: "Reece James", position: 25 },
        { id: 24, name: "Rodri", position: 26 },
        { id: 59, name: "Ben White", position: 27 },
        { id: 25, name: "Phil Foden", position: 28 },
        { id: 60, name: "John Stones", position: 29 }
    ],
    27: [
        { id: 26, name: "Bernardo Silva", position: 0 },
        { id: 61, name: "Jurrien Timber", position: 1 },
        { id: 27, name: "Luka Modrić", position: 2 },
        { id: 62, name: "Cole Palmer", position: 3 },
        { id: 28, name: "Toni Kroos", position: 4 },
        { id: 63, name: "Bruno Guimarães", position: 5 },
        { id: 29, name: "Joshua Kimmich", position: 6 },
        { id: 64, name: "Jarrod Bowen", position: 7 },
        { id: 30, name: "Declan Rice", position: 8 },
        { id: 65, name: "Dominik Szoboszlai", position: 9 },
        { id: 1, name: "Lionel Messi", position: 10 },
        { id: 31, name: "Martin Ødegaard", position: 11 },
        { id: 2, name: "Cristiano Ronaldo", position: 12 },
        { id: 32, name: "Bruno Fernandes", position: 13 },
        { id: 3, name: "Kylian Mbappé", position: 14 },
        { id: 33, name: "Frenkie de Jong", position: 15 },
        { id: 4, name: "Erling Haaland", position: 16 },
        { id: 34, name: "Federico Valverde", position: 17 },
        { id: 5, name: "Neymar", position: 18 },
        { id: 35, name: "Jamal Musiala", position: 19 },
        { id: 41, name: "Virgil van Dijk", position: 20 },
        { id: 6, name: "Mohamed Salah", position: 21 },
        { id: 42, name: "Sergio Ramos", position: 22 },
        { id: 7, name: "Vinícius Júnior", position: 23 },
        { id: 43, name: "Antonio Rüdiger", position: 24 },
        { id: 8, name: "Harry Kane", position: 25 },
        { id: 44, name: "Rúben Dias", position: 26 },
        { id: 36, name: "Lamine Yamal", position: 27 },
        { id: 45, name: "Marquinhos", position: 28 },
        { id: 37, name: "Enzo Fernández", position: 29 }
    ],
    28: [
        { id: 46, name: "João Cancelo", position: 0 },
        { id: 9, name: "Sadio Mané", position: 1 },
        { id: 47, name: "Trent Alexander-Arnold", position: 2 },
        { id: 10, name: "Son Heung-min", position: 3 },
        { id: 48, name: "Achraf Hakimi", position: 4 },
        { id: 11, name: "Robert Lewandowski", position: 5 },
        { id: 49, name: "Theo Hernández", position: 6 },
        { id: 12, name: "Victor Osimhen", position: 7 },
        { id: 50, name: "Jules Koundé", position: 8 },
        { id: 13, name: "Antoine Griezmann", position: 9 },
        { id: 51, name: "William Saliba", position: 10 },
        { id: 14, name: "Lautaro Martínez", position: 11 },
        { id: 52, name: "Gabriel Magalhães", position: 12 },
        { id: 15, name: "Julián Álvarez", position: 13 },
        { id: 53, name: "Matthijs de Ligt", position: 14 },
        { id: 16, name: "Viktor Gyökeres", position: 15 },
        { id: 54, name: "Alphonso Davies", position: 16 },
        { id: 17, name: "Bukayo Saka", position: 17 },
        { id: 55, name: "Kyle Walker", position: 18 },
        { id: 18, name: "Khvicha Kvaratskhelia", position: 19 },
        { id: 56, name: "Dayot Upamecano", position: 20 },
        { id: 19, name: "Marcus Rashford", position: 21 },
        { id: 57, name: "Éder Militão", position: 22 },
        { id: 20, name: "Rafael Leão", position: 23 },
        { id: 58, name: "Reece James", position: 24 },
        { id: 21, name: "Kevin De Bruyne", position: 25 },
        { id: 59, name: "Ben White", position: 26 },
        { id: 22, name: "Jude Bellingham", position: 27 },
        { id: 60, name: "John Stones", position: 28 },
        { id: 23, name: "Pedri", position: 29 }
    ],
    29: [
        { id: 24, name: "Rodri", position: 0 },
        { id: 61, name: "Jurrien Timber", position: 1 },
        { id: 25, name: "Phil Foden", position: 2 },
        { id: 62, name: "Cole Palmer", position: 3 },
        { id: 26, name: "Bernardo Silva", position: 4 },
        { id: 63, name: "Bruno Guimarães", position: 5 },
        { id: 27, name: "Luka Modrić", position: 6 },
        { id: 64, name: "Jarrod Bowen", position: 7 },
        { id: 28, name: "Toni Kroos", position: 8 },
        { id: 65, name: "Dominik Szoboszlai", position: 9 },
        { id: 29, name: "Joshua Kimmich", position: 10 },
        { id: 1, name: "Lionel Messi", position: 11 },
        { id: 30, name: "Declan Rice", position: 12 },
        { id: 2, name: "Cristiano Ronaldo", position: 13 },
        { id: 31, name: "Martin Ødegaard", position: 14 },
        { id: 3, name: "Kylian Mbappé", position: 15 },
        { id: 32, name: "Bruno Fernandes", position: 16 },
        { id: 4, name: "Erling Haaland", position: 17 },
        { id: 33, name: "Frenkie de Jong", position: 18 },
        { id: 5, name: "Neymar", position: 19 },
        { id: 34, name: "Federico Valverde", position: 20 },
        { id: 6, name: "Mohamed Salah", position: 21 },
        { id: 35, name: "Jamal Musiala", position: 22 },
        { id: 38, name: "Eduardo Camavinga", position: 23 },
        { id: 39, name: "Florian Wirtz", position: 24 },
        { id: 40, name: "James Maddison", position: 25 },
        { id: 7, name: "Vinícius Júnior", position: 26 },
        { id: 8, name: "Harry Kane", position: 27 },
        { id: 9, name: "Sadio Mané", position: 28 },
        { id: 10, name: "Son Heung-min", position: 29 }
    ],
    30: [
        { id: 11, name: "Robert Lewandowski", position: 0 },
        { id: 12, name: "Victor Osimhen", position: 1 },
        { id: 13, name: "Antoine Griezmann", position: 2 },
        { id: 14, name: "Lautaro Martínez", position: 3 },
        { id: 15, name: "Julián Álvarez", position: 4 },
        { id: 16, name: "Viktor Gyökeres", position: 5 },
        { id: 17, name: "Bukayo Saka", position: 6 },
        { id: 18, name: "Khvicha Kvaratskhelia", position: 7 },
        { id: 19, name: "Marcus Rashford", position: 8 },
        { id: 20, name: "Rafael Leão", position: 9 },
        { id: 36, name: "Lamine Yamal", position: 10 },
        { id: 41, name: "Virgil van Dijk", position: 11 },
        { id: 42, name: "Sergio Ramos", position: 12 },
        { id: 43, name: "Antonio Rüdiger", position: 13 },
        { id: 44, name: "Rúben Dias", position: 14 },
        { id: 45, name: "Marquinhos", position: 15 },
        { id: 46, name: "João Cancelo", position: 16 },
        { id: 47, name: "Trent Alexander-Arnold", position: 17 },
        { id: 48, name: "Achraf Hakimi", position: 18 },
        { id: 49, name: "Theo Hernández", position: 19 },
        { id: 50, name: "Jules Koundé", position: 20 },
        { id: 51, name: "William Saliba", position: 21 },
        { id: 52, name: "Gabriel Magalhães", position: 22 },
        { id: 53, name: "Matthijs de Ligt", position: 23 },
        { id: 54, name: "Alphonso Davies", position: 24 },
        { id: 55, name: "Kyle Walker", position: 25 },
        { id: 56, name: "Dayot Upamecano", position: 26 },
        { id: 57, name: "Éder Militão", position: 27 },
        { id: 58, name: "Reece James", position: 28 },
        { id: 59, name: "Ben White", position: 29 }
    ]
};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { PREDETERMINED_ROUNDS };
}
