// 90 Words Database for Guess The Word Game
// Football-related terms, famous players, teams, and stadiums

const WORDS_DATABASE = [
    // FOOTBALL TERMS (30)
    { id: 1, word: "GOALKEEPER", category: "Position" },
    { id: 2, word: "DEFENDER", category: "Position" },
    { id: 3, word: "MIDFIELDER", category: "Position" },
    { id: 4, word: "FORWARD", category: "Position" },
    { id: 5, word: "STRIKER", category: "Position" },
    { id: 6, word: "WINGER", category: "Position" },
    { id: 7, word: "CAPTAIN", category: "Role" },
    { id: 8, word: "MANAGER", category: "Role" },
    { id: 9, word: "REFEREE", category: "Role" },
    { id: 10, word: "LINESMAN", category: "Role" },
    { id: 11, word: "PENALTY", category: "Term" },
    { id: 12, word: "CORNER", category: "Term" },
    { id: 13, word: "OFFSIDE", category: "Term" },
    { id: 14, word: "HEADER", category: "Term" },
    { id: 15, word: "VOLLEY", category: "Term" },
    { id: 16, word: "DRIBBLE", category: "Term" },
    { id: 17, word: "TACKLE", category: "Term" },
    { id: 18, word: "PASSING", category: "Term" },
    { id: 19, word: "SHOOTING", category: "Term" },
    { id: 20, word: "SAVINGS", category: "Term" },
    { id: 21, word: "FORMATION", category: "Term" },
    { id: 22, word: "SUBSTITUTE", category: "Term" },
    { id: 23, word: "INJURY", category: "Term" },
    { id: 24, word: "VAR", category: "Term" },
    { id: 25, word: "FLAG", category: "Term" },
    { id: 26, word: "WHISTLE", category: "Term" },
    { id: 27, word: "KICKOFF", category: "Term" },
    { id: 28, word: "HALFTIME", category: "Term" },
    { id: 29, word: "FULLTIME", category: "Term" },
    { id: 30, word: "EXTRA", category: "Term" },
    
    // FAMOUS PLAYERS (30)
    { id: 31, word: "PELE", category: "Legend" },
    { id: 32, word: "MARADONA", category: "Legend" },
    { id: 33, word: "ZIDANE", category: "Legend" },
    { id: 34, word: "RONALDINHO", category: "Legend" },
    { id: 35, word: "BECKHAM", category: "Legend" },
    { id: 36, word: "ROONEY", category: "Legend" },
    { id: 37, word: "SHEARER", category: "Legend" },
    { id: 38, word: "HENRY", category: "Legend" },
    { id: 39, word: "GERRARD", category: "Legend" },
    { id: 40, word: "LAMPARD", category: "Legend" },
    { id: 41, word: "TERRY", category: "Legend" },
    { id: 42, word: "FERDINAND", category: "Legend" },
    { id: 43, word: "NESTA", category: "Legend" },
    { id: 44, word: "MALDINI", category: "Legend" },
    { id: 45, word: "BUFFON", category: "Legend" },
    { id: 46, word: "CASILLAS", category: "Legend" },
    { id: 47, word: "CAFU", category: "Legend" },
    { id: 48, word: "ROBERTO", category: "Legend" },
    { id: 49, word: "KAKA", category: "Legend" },
    { id: 50, word: "RIVALDO", category: "Legend" },
    { id: 51, word: "FIGO", category: "Legend" },
    { id: 52, word: "RAUL", category: "Legend" },
    { id: 53, word: "SHEVCHENKO", category: "Legend" },
    { id: 54, word: "DROGBA", category: "Legend" },
    { id: 55, word: "LAMPARD", category: "Legend" },
    { id: 56, word: "GERARD", category: "Legend" },
    { id: 57, word: "SCHOLES", category: "Legend" },
    { id: 58, word: "GIGGS", category: "Legend" },
    { id: 59, word: "BECKENBAUER", category: "Legend" },
    { id: 60, word: "CRUYFF", category: "Legend" },
    
    // TEAMS & STADIUMS (30)
    { id: 61, word: "MADRID", category: "Team" },
    { id: 62, word: "BARCELONA", category: "Team" },
    { id: 63, word: "MANCHESTER", category: "Team" },
    { id: 64, word: "LIVERPOOL", category: "Team" },
    { id: 65, word: "CHELSEA", category: "Team" },
    { id: 66, word: "ARSENAL", category: "Team" },
    { id: 67, word: "TOTTENHAM", category: "Team" },
    { id: 68, word: "JUVENTUS", category: "Team" },
    { id: 69, word: "MILAN", category: "Team" },
    { id: 70, word: "INTER", category: "Team" },
    { id: 71, word: "NAPOLI", category: "Team" },
    { id: 72, word: "ROMA", category: "Team" },
    { id: 73, word: "BAYERN", category: "Team" },
    { id: 74, word: "DORTMUND", category: "Team" },
    { id: 75, word: "PSG", category: "Team" },
    { id: 76, word: "AJAX", category: "Team" },
    { id: 77, word: "PORTO", category: "Team" },
    { id: 78, word: "BENFICA", category: "Team" },
    { id: 79, word: "SPORTING", category: "Team" },
    { id: 80, word: "SEVILLA", category: "Team" },
    { id: 81, word: "VALENCIA", category: "Team" },
    { id: 82, word: "ATLETICO", category: "Team" },
    { id: 83, word: "WEMBLEY", category: "Stadium" },
    { id: 84, word: "CAMPNOU", category: "Stadium" },
    { id: 85, word: "BERNABEU", category: "Stadium" },
    { id: 86, word: "OLDTRAFFORD", category: "Stadium" },
    { id: 87, word: "ANFIELD", category: "Stadium" },
    { id: 88, word: "SANSIRO", category: "Stadium" },
    { id: 89, word: "ALLIANZ", category: "Stadium" },
    { id: 90, word: "MARACANA", category: "Stadium" }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { WORDS_DATABASE };
}
